In [1]:
import tensorflow as tf

In [2]:
x = tf.Variable([[2.0, 3.0, 1.0]])
y = tf.Variable([[-4.0, 3.0, 2.0]])

In [3]:
x

<tf.Variable 'Variable:0' shape=(1, 3) dtype=float32, numpy=array([[2., 3., 1.]], dtype=float32)>

In [4]:
y

<tf.Variable 'Variable:0' shape=(1, 3) dtype=float32, numpy=array([[-4.,  3.,  2.]], dtype=float32)>

In [5]:
with tf.GradientTape() as tape:
    f = (x + y) ** 2 + 2 * x * y
df = tape.gradient(f, [x, y])

In [6]:
df

[<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[-12.,  18.,  10.]], dtype=float32)>,
 <tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[ 0., 18.,  8.]], dtype=float32)>]

---

In [7]:
x = tf.Variable([[-1.0]])

In [8]:
y = lambda: x ** 2 - x

In [18]:
N = 1000

In [19]:
opt = tf.optimizers.legacy.SGD(learning_rate=0.01)
for i in range(N):    
    opt.minimize(y, [x])

In [20]:
x

<tf.Variable 'Variable:0' shape=(1, 1) dtype=float32, numpy=array([[0.49999928]], dtype=float32)>

---

In [21]:
a = tf.constant(1)
a

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [27]:
b = tf.constant([1, 2, 3, 4])
b

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [26]:
c = tf.constant([[1, 2, 3], 
                 [1, 2, 3], 
                 [1, 2, 3]], dtype=tf.float16)
c

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]], dtype=float16)>

In [29]:
c = tf.cast(c, dtype=tf.int32)
c

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]], dtype=int32)>

In [30]:
import numpy as np
b = np.array(b)
b

array([1, 2, 3, 4], dtype=int32)

In [31]:
c = c.numpy()
c

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]], dtype=int32)

In [32]:
c = tf.Variable([[1, 2, 3], 
                 [1, 2, 3], 
                 [1, 2, 3]], dtype=tf.float16)
c

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float16, numpy=
array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]], dtype=float16)>

In [33]:
c.assign([[4, 5, 6], 
          [4, 5, 6], 
          [4, 5, 6]])

<tf.Variable 'UnreadVariable' shape=(3, 3) dtype=float16, numpy=
array([[4., 5., 6.],
       [4., 5., 6.],
       [4., 5., 6.]], dtype=float16)>

In [35]:
c.assign_add([[4, 5, 6], 
              [4, 5, 6], 
              [4, 5, 6]])

<tf.Variable 'UnreadVariable' shape=(3, 3) dtype=float16, numpy=
array([[ 8., 10., 12.],
       [ 8., 10., 12.],
       [ 8., 10., 12.]], dtype=float16)>

In [36]:
c.assign_sub([[4, 5, 6], 
              [4, 5, 6], 
              [4, 5, 6]])

<tf.Variable 'UnreadVariable' shape=(3, 3) dtype=float16, numpy=
array([[4., 5., 6.],
       [4., 5., 6.],
       [4., 5., 6.]], dtype=float16)>

In [37]:
c.shape

TensorShape([3, 3])

In [38]:
a.shape

TensorShape([])

In [42]:
c[2, 2]

<tf.Tensor: shape=(), dtype=float16, numpy=6.0>

In [43]:
c[2][2]

<tf.Tensor: shape=(), dtype=float16, numpy=6.0>

In [45]:
c[:, 2]

<tf.Tensor: shape=(3,), dtype=float16, numpy=array([6., 6., 6.], dtype=float16)>

In [54]:
d = tf.range(25)
d = tf.reshape(d, (5, 5))
d

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]], dtype=int32)>

In [57]:
d_t = tf.transpose(d, perm=(1, 0))
d_t

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[ 0,  5, 10, 15, 20],
       [ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24]], dtype=int32)>

---

In [59]:
a = tf.zeros(shape=(5,5))
a

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [60]:
a = tf.ones(shape=(5,5))
a

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [62]:
a = tf.ones_like(d_t)
a

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)>

In [63]:
a = tf.zeros_like(b)
a

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 0, 0, 0], dtype=int32)>

In [64]:
z = tf.eye(7)
z

<tf.Tensor: shape=(7, 7), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]], dtype=float32)>

In [65]:
z = tf.eye(5, 3)
z

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [66]:
z = tf.fill((5, 3), -1)
z

<tf.Tensor: shape=(5, 3), dtype=int32, numpy=
array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1]], dtype=int32)>

In [72]:
s = tf.random.uniform(shape=(2,4), dtype=tf.int32, maxval=10)
s

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[6, 9, 0, 3],
       [7, 2, 0, 4]], dtype=int32)>

In [76]:
s = tf.random.normal((2,4), 0, 0.1)
s

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[-0.06400489,  0.14902513, -0.02986988, -0.04679237],
       [-0.00449683,  0.03791625, -0.07655275, -0.04150017]],
      dtype=float32)>

In [84]:
tf.random.set_seed(1)

In [85]:
s = tf.random.normal((2,4), 0, 0.1)
s

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[-0.11012203,  0.15457517,  0.0383644 , -0.08796579],
       [-0.12246722, -0.09811211,  0.00878078, -0.02032604]],
      dtype=float32)>

In [86]:
tf.random.set_seed(1)

In [87]:
s = tf.random.normal((2,4), 0, 0.1)
s

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[-0.11012203,  0.15457517,  0.0383644 , -0.08796579],
       [-0.12246722, -0.09811211,  0.00878078, -0.02032604]],
      dtype=float32)>

---

In [88]:
a = tf.Variable([1, 2, 4])
b = tf.Variable([4, 8, 4])

In [89]:
tf.add(a, b)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 5, 10,  8], dtype=int32)>

In [90]:
a + b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 5, 10,  8], dtype=int32)>

In [91]:
tf.subtract(a, b)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-3, -6,  0], dtype=int32)>

In [92]:
a - b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-3, -6,  0], dtype=int32)>

In [94]:
tf.divide(a, b)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.25, 0.25, 1.  ])>

In [96]:
a / b

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.25, 0.25, 1.  ])>

In [97]:
a // b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 0, 1], dtype=int32)>

In [98]:
a % b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 0], dtype=int32)>

In [99]:
tf.multiply(a, b)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 4, 16, 16], dtype=int32)>

In [100]:
a * b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 4, 16, 16], dtype=int32)>

In [102]:
a ** 2

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 1,  4, 16], dtype=int32)>

In [103]:
a ** b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([  1, 256, 256], dtype=int32)>

In [104]:
tf.tensordot(a, b, axes=0)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 4,  8,  4],
       [ 8, 16,  8],
       [16, 32, 16]], dtype=int32)>

In [106]:
tf.tensordot(a, b, axes=1)

<tf.Tensor: shape=(), dtype=int32, numpy=36>

In [116]:
g = tf.range(20)
g = tf.reshape(g, shape=(4,5))
g = tf.Variable(g)

f = tf.range(20)
f = tf.reshape(f, shape=(5,4))
f = tf.Variable(f)

In [118]:
x = tf.matmul(g, f)
x

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[120, 130, 140, 150],
       [320, 355, 390, 425],
       [520, 580, 640, 700],
       [720, 805, 890, 975]], dtype=int32)>

In [121]:
tf.tensordot(g, f, axes=1)

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[120, 130, 140, 150],
       [320, 355, 390, 425],
       [520, 580, 640, 700],
       [720, 805, 890, 975]], dtype=int32)>

In [133]:
g @ f

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[120, 130, 140, 150],
       [320, 355, 390, 425],
       [520, 580, 640, 700],
       [720, 805, 890, 975]], dtype=int32)>

In [134]:
aa = tf.reduce_sum(x)
aa

<tf.Tensor: shape=(), dtype=int32, numpy=7860>

In [135]:
aa = tf.reduce_sum(x, axis=0)
aa

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1680, 1870, 2060, 2250], dtype=int32)>

In [136]:
aa = tf.reduce_sum(x, axis=1)
aa

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 540, 1490, 2440, 3390], dtype=int32)>

In [137]:
aa = tf.reduce_mean(x)
aa

<tf.Tensor: shape=(), dtype=int32, numpy=491>

In [138]:
aa = tf.reduce_max(x)
aa

<tf.Tensor: shape=(), dtype=int32, numpy=975>

In [139]:
aa = tf.reduce_min(x)
aa

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [140]:
aa = tf.reduce_prod(x)
aa

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [143]:
aa = tf.sqrt(tf.cast(x, dtype=tf.float32))
aa

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[10.954452, 11.401754, 11.83216 , 12.247449],
       [17.888544, 18.841444, 19.748417, 20.615528],
       [22.803509, 24.083189, 25.298222, 26.457514],
       [26.832815, 28.372522, 29.832869, 31.22499 ]], dtype=float32)>

In [144]:
aa = tf.square(x)
aa

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[ 14400,  16900,  19600,  22500],
       [102400, 126025, 152100, 180625],
       [270400, 336400, 409600, 490000],
       [518400, 648025, 792100, 950625]], dtype=int32)>

In [146]:
tf.sin(tf.cast(x, dtype=tf.float32))

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[ 5.8061117e-01, -9.3010598e-01,  9.8023969e-01, -7.1487641e-01],
       [-4.2815542e-01, -3.0144352e-05,  4.2820993e-01, -7.7390975e-01],
       [-9.9779528e-01,  9.3008381e-01, -7.7385253e-01,  5.4397053e-01],
       [-5.4407167e-01,  6.8330568e-01, -8.0118871e-01,  8.9403719e-01]],
      dtype=float32)>

---

In [161]:
w = tf.Variable(tf.random.normal((3,2)))
b = tf.Variable(tf.zeros(2), dtype=tf.float32)
x = tf.Variable([[-2.0, 1.0, 3.0]])

with tf.GradientTape() as tape:
    y = x @ w + b
    loss = tf.reduce_mean(y ** 2)
    
df = tape.gradient(loss, [w, b])
df

[<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-10.468376 ,   1.4664106],
        [  5.234188 ,  -0.7332053],
        [ 15.702564 ,  -2.199616 ]], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 5.234188 , -0.7332053], dtype=float32)>]

In [162]:
w = tf.Variable(tf.random.normal((3,2)))
b = tf.Variable(tf.zeros(2), dtype=tf.float32, trainable=False)
x = tf.Variable([[-2.0, 1.0, 3.0]])

with tf.GradientTape() as tape:
    y = x @ w + b
    loss = tf.reduce_mean(y ** 2)
    
df = tape.gradient(loss, [w, b])
df

[<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ -6.2120395,   6.7735443],
        [  3.1060197,  -3.3867722],
        [  9.318059 , -10.160316 ]], dtype=float32)>,
 None]

In [163]:
w = tf.Variable(tf.random.normal((3,2)))
b = tf.Variable(tf.zeros(2), dtype=tf.float32)
x = tf.Variable([[-2.0, 1.0, 3.0]])

with tf.GradientTape(watch_accessed_variables=False) as tape:
    tape.watch(w)
    y = x @ w + b
    loss = tf.reduce_mean(y ** 2)
    
df = tape.gradient(loss, [w, b])
df

[<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[  1.4762301, -14.969099 ],
        [ -0.7381151,   7.4845495],
        [ -2.2143452,  22.453648 ]], dtype=float32)>,
 None]